export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_BOOKS_FROM_SEARCH_REQUEST = 'GET_BOOKS_FROM_SEARCH_REQUEST';
export const GET_BOOKS_FROM_SEARCH_SUCCESS = 'GET_BOOKS_FROM_SEARCH_SUCCESS';
export const GET_BOOKS_FROM_SEARCH_FAILURE = 'GET_BOOKS_FROM_SEARCH_FAILURE';

export const GET_BOOKS_FROM_FULLSEARCH_REQUEST = 'GET_BOOKS_FROM_FULLSEARCH_REQUEST';
export const GET_BOOKS_FROM_FULLSEARCH_SUCCESS = 'GET_BOOKS_FROM_FULLSEARCH_SUCCESS';
export const GET_BOOKS_FROM_FULLSEARCH_FAILURE = 'GET_BOOKS_FROM_FULLSEARCH_FAILURE';

export const BOOK_POST_DATA_SUCCESS = 'BOOK_POST_DATA_SUCCESS';
export const BOOK_POST_DATA_FAILURE = 'BOOK_POST_DATA_FAILURE';

export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAILURE = 'GET_LANGUAGES_FAILURE';

export const LANGUAGE_POST_DATA_SUCCESS = 'LANGUAGE_POST_DATA_SUCCESS';
export const LANGUAGE_POST_DATA_FAILURE = 'LANGUAGE_POST_DATA_FAILURE';

export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAILURE = 'GET_STATUS_FAILURE';
export const POST_STATUS_SUCCESS = 'POST_STATUS_SUCCESS';
export const POST_STATUS_FAILURE = 'POST_STATUS_FAILURE';

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

<<<<<<< HEAD
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
=======
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE';
>>>>>>> bec46e4bd0f4f7ed2325fe3e3f2b50304ce19b4b
