export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_BOOKS_FROM_SEARCH_REQUEST = 'GET_BOOKS_FROM_SEARCH_REQUEST';
export const GET_BOOKS_FROM_SEARCH_SUCCESS = 'GET_BOOKS_FROM_SEARCH_SUCCESS';
export const GET_BOOKS_FROM_SEARCH_FAILURE = 'GET_BOOKS_FROM_SEARCH_FAILURE';

export const GET_BOOKS_FROM_FULLSEARCH_REQUEST = 'GET_BOOKS_FROM_FULLSEARCH_REQUEST';
export const GET_BOOKS_FROM_FULLSEARCH_SUCCESS = 'GET_BOOKS_FROM_FULLSEARCH_SUCCESS';
export const GET_BOOKS_FROM_FULLSEARCH_FAILURE = 'GET_BOOKS_FROM_FULLSEARCH_FAILURE';

export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAILURE = 'GET_LANGUAGES_FAILURE';


